# Site settings
title: "Symposium on Visualization in Data Science (VDS at IEEE VIS 2015)"
email: "webmaster@dbvis.de"
description: "Symposium on Visualization in Data Science (VDS at IEEE VIS 2015)"
baseurl: "/2015"
url: "http://visualdatascience.org"
conferenceshort: "VDS 2015"
conferencedate: "Monday, October 26th, 2015"

deadline_submission: "July 1, 2015 5:00pm PDT"
deadline_notification: "September 4, 2015"
deadline_camera: "September 18, 2015"

deadline_poster: "August 15, 2015 5:00pm PDT"

# Build settings
markdown: kramdown